package com.bookshop.entities;
// Generated Jan 5, 2018 5:58:02 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "book", catalog = "book_shop")
public class Book implements java.io.Serializable {

	private Integer id;
	private Author author;
	private BookType bookType;
	private Publisher publisher;
	private String name;
	private String image;
	private String isbn;
	private Integer stock;
	private Integer rootPrice;
	private Integer currentPrice;
	private boolean enabled;
	private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);

	public Book() {
	}

	public Book(Author author, BookType bookType, Publisher publisher, String name, String image,String isbn, Integer stock, Integer rootPrice,
			Integer currentPrice, boolean enabled, Set<OrderDetail> orderDetails) {
		this.author = author;
		this.bookType = bookType;
		this.publisher = publisher;
		this.name = name;
		this.isbn = isbn;
		this.stock = stock;
		this.rootPrice = rootPrice;
		this.currentPrice = currentPrice;
		this.enabled = enabled;
		this.orderDetails = orderDetails;
		this.image = image;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "author")
	public Author getAuthor() {
		return this.author;
	}

	public void setAuthor(Author author) {
		this.author = author;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type")
	public BookType getBookType() {
		return this.bookType;
	}

	public void setBookType(BookType bookType) {
		this.bookType = bookType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "publisher")
	public Publisher getPublisher() {
		return this.publisher;
	}

	public void setPublisher(Publisher publisher) {
		this.publisher = publisher;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@Column(name = "image", length = 255)
	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}
	
	@Column(name = "isbn", length = 15)
	public String getIsbn() {
		return isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	@Column(name = "stock")
	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	@Column(name = "root_price")
	public Integer getRootPrice() {
		return this.rootPrice;
	}

	public void setRootPrice(Integer rootPrice) {
		this.rootPrice = rootPrice;
	}

	@Column(name = "current_price")
	public Integer getCurrentPrice() {
		return this.currentPrice;
	}

	public void setCurrentPrice(Integer currentPrice) {
		this.currentPrice = currentPrice;
	}
	
	

	@Column(name = "enabled")
	public boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "book")
	public Set<OrderDetail> getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set<OrderDetail> orderDetails) {
		this.orderDetails = orderDetails;
	}

}
